<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\Builder' => $strauss_src . '/vena/wp-settings-builder/src/php/Builder.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\Field' => $strauss_src . '/vena/wp-settings-builder/src/php/Field.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\Section' => $strauss_src . '/vena/wp-settings-builder/src/php/Section.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Email' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Email.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Radio' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Radio.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Url' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Url.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Html' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Html.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Generic' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Generic.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Textarea' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Textarea.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Select' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Select.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Checkbox' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Checkbox.php',
   'CUMULUS\Gutenberg\Tools\Vendors\vena\WordpressSettingsBuilder\FieldTypes\Text' => $strauss_src . '/vena/wp-settings-builder/src/php/FieldTypes/Text.php',
);